# This is a basic workflow to help you get started with Actions

name: Run Detekt Check

# Controls when the workflow will run
on:
  push:

jobs:
  Run-Detekt:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: SetUp Maps Key
        env:
          MAPS_API_KEY: ${{"Some Key"}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties

      - name: Run detekt
        run: ./gradlew detekt
      # TODO -> Solve this
      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
#      - name: Upload SARIF to Github using the upload-sarif action
#        uses: github/codeql-action/upload-sarif@v2
#        if: success() || failure()
#        with:
#          sarif_file: build/reports/detekt/detekt.sarif