# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
    - name: Detekt all
  # You may pin to the exact commit or the version.
  # uses: natiginfo/action-detekt-all@07143c2b2a6dacadedb5e5d209f3c615bdcfe5ac
      uses: natiginfo/action-detekt-all@1.22.0
